name: "Publish on NPM"
on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.actor != 'prisma-bot' # Prevents an infinite job loop
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@prisma"
      - name: Install dependencies
        run: yarn
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Prismo"
          git config --global user.email "prismabots@gmail.com"
          yarn version --patch
          yarn publish
          git push https://$PRISMO_PAT@github.com/prisma/lens.git --follow-tags
