name: "Publish on NPM"
on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@prisma"
      - name: Install dependencies
        run: npm ci
      # - name: Publish to NPM
      #   run: |
      #     git config --global user.name "Prismo"
      #     git config --global user.email "prismabots@gmail.com"
      #     npm version patch
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create empty commit
        env:
          PRISMO_PAT: ${{ secrets.PRISMO_PAT }}
        run: |
          git config --global user.name "Prismo"
          git config --global user.email "prismabots@gmail.com"
          git commit -m "Trigger release" --allow-empty
          git push https://$PRISMO_PAT@github.com/prisma/lens.git
